name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:

  release:

    name: Release

    runs-on: ubuntu-latest

    # if: ${{ github.event.pull_request.merged == true && github.base_ref == 'main' && contains(github.base_ref, 'release/') }}

    steps:

    - run: |
        echo ${{ github.event.pull_request.merged }}
        echo ${{ github.base_ref }}
        echo ${{ contains(github.base_ref, 'release/') }}
        echo ${{ github.base_ref }}

    - uses: actions/checkout@v2

    - run: echo $GITHUB_HEAD_REF | sed 's|release/||' | { printf '::set-output name=TAG_NAME::'; cat; }
      id: output

    - uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.output.outputs.TAG_NAME }}
